#!/bin/bash
#All starts here

############################################################################################
# Update the values as per your requirements
############################################################################################
digikubeCoreRawRepoUrl="https://raw.githubusercontent.com/samdesh-gcp1/digikube-core/master"
digikubeInstanceRawRepoUrl="https://raw.githubusercontent.com/samdesh-gcp1/c1-dev1/master"

#Following values are also set in bastion-init-shell...  be consistent
digikubeMasterProject="digikube-master3"
digikubeCoreRepoAccessTokenName="digikube-core-repo-access-token"
digikubeCoreRepoAccessTokenVersion="2"
digikubeInstanceRepoAccessTokenName="digikube-instance-repo-access-token"
digikubeInstanceRepoAccessTokenVersion="2"

tempMasterProject=$(gcloud projects list --filter="project_id=${digikubeMasterProject}" --format="value(project_id)")
if [[ "${digikubeMasterProject}" == "${tempMasterProjectId}" ]]; then
	temp1=1
else
	echo "Master project: ${digikubeMasterProject} does not exists.  Exiting..."
	exit 1
fi

digikubeCoreRepoAccessTokenValue=$(gcloud beta secrets versions access ${digikubeCoreRepoAccessTokenVersion} --secret=${digikubeCoreRepoAccessTokenName} --project=${digikubeMasterProject})
digikubeInstanceRepoAccessTokenValue=$(gcloud beta secrets versions access ${digikubeInstanceRepoAccessTokenVersion} --secret=${digikubeInstanceRepoAccessTokenName} --project=${digikubeMasterProject})

tmpExecDir=$(mktemp -d --suffix="-digikube")
bootstrapShell="${tmpExecDir}/bootstrap"

wget --quiet --no-cache --header="Authorization: token ${digikubeInstanceRepoAccessTokenValue}" -O "${bootstrapShell}" "${digikubeCoreRawRepoUrl}/cloud-init/bootstrap"

chmod +x ${bootstrapShell}

${bootstrapShell} ${digikubeMasterProject} ${digikubeCoreRepoAccessTokenName} ${digikubeCoreRepoAccessTokenVersion} ${digikubeCoreRepoAccessTokenValue} ${digikubeCoreRawRepoUrl} ${digikubeInstanceRepoAccessTokenName} ${digikubeInstanceRepoAccessTokenVersion} ${digikubeInstanceRepoAccessTokenValue} ${digikubeInstanceRawRepoUrl} create

rm -rf "${tmpExecDir}"

digikubeCoreRepoAccessToken=""
digikubeInstanceRepoAccessToken=""

unset digikubeCoreRepoAccessToken
unset digikubeInstanceRepoAccessToken
