#!/bin/bash
# Main script to create master setup

# Input parameters - none 

DIGIKUBE_MASTER_PROJECT="digikube-master3"
DIGIKUBE_GITHUB_ACCESS_TOKEN_SECRET="digikube-github-access-token-secret"

#################################################################
# Create master project
#----------------------------------------------------------------

getMasterProject=$(gcloud projects list --filter="project_id=${DIGIKUBE_MASTER_PROJECT}" | grep "${DIGIKUBE_MASTER_PROJECT}" |  awk '{print $1}')
if [[ $? -gt 0 ]]; then
	echo "WARN: Error while checking availability of ${DIGIKUBE_MASTER_PROJECT} project.  Exiting..."
	exit 1
else
	if [[ "${getMasterProject}" == "${DIGIKUBE_MASTER_PROJECT}" ]]; then
		echo "INFO: ${DIGIKUBE_MASTER_PROJECT} project already available.  Reusing existing project."
	else
		gcloud projects create "${DIGIKUBE_MASTER_PROJECT}" --labels="group=digikube,version=0_1" --name="${DIGIKUBE_MASTER_PROJECT}"
		if [[ $? -gt 0 ]]; then
			echo "ERROR: Error while creating ${DIGIKUBE_MASTER_PROJECT} project"
		else
			echo "INFO: Created ${DIGIKUBE_MASTER_PROJECT} project"
		fi
	fi
	billingAccountList=$(gcloud alpha billing accounts list)
	billingAccountCount=$(echo -n "${billingAccountList}" | grep -c '^')
	if [[ ${billingAccountCount} -lt 1 ]]; then
		echo "No billing account available.  Exiting..."
		exit 1
	else
		if [[ ${billingAccountCount} -eq 2 ]]; then
			billingAccountId=$(echo "$(gcloud alpha billing accounts list)" | sed -n 2p | awk '{print $1}')
		else
			echo "SR# $("$(gcloud alpha billing accounts list)" | sed -n 1p)"
			for (( c=2; c<=${billingAccountCount}; c++ ))
			do  
				echo " $($c-1) $(gcloud alpha billing accounts list | sed -n ${billingAccountSelect}p)"
			done
			read -p "Please enter the row number for the billing account to use.  Ignore the header row. : " billingAccountSelect
			billingAccountSelect=${billingAccountSelect}+1
			billingAccountId=$("$(gcloud alpha billing accounts list)" | sed -n ${billingAccountSelect}p | awk '{print $1}')
		fi
		echo "gcloud beta billing projects link ${DIGIKUBE_MASTER_PROJECT} --billing-account=${billingAccountId}"
		gcloud --quiet beta billing projects link "${DIGIKUBE_MASTER_PROJECT}" --billing-account="${billingAccountId}"
	fi
fi

#################################################################
# Enable secretmanager.googleapis.com API
#----------------------------------------------------------------
gcloud services enable secretmanager.googleapis.com --project="${DIGIKUBE_MASTER_PROJECT}"
if [[ $? -gt 0 ]]; then
	echo "ERROR: Error while enabling service secretmanager.googleapis.com for project ${DIGIKUBE_MASTER_PROJECT} project.  Exiting..."
	exit 1
else
	echo "INFO: Enabled service secretmanager.googleapis.com for project ${DIGIKUBE_MASTER_PROJECT} project"
fi


#################################################################
# Create secret to hold github access token
#----------------------------------------------------------------

getGithubAccessTokenSecret=$(gcloud --quiet beta secrets list --project="${DIGIKUBE_MASTER_PROJECT}" --filter="${DIGIKUBE_GITHUB_ACCESS_TOKEN_SECRET}"| grep "${DIGIKUBE_GITHUB_ACCESS_TOKEN_SECRET}" |  awk '{print $1}')
if [[ $? -gt 0 ]]; then
	echo "WARN: Error while checking availability of ${DIGIKUBE_GITHUB_ACCESS_TOKEN_SECRET} secret.  Exiting..."
else
	if [[ "${getGithubAccessTokenSecret}" == "${DIGIKUBE_GITHUB_ACCESS_TOKEN_SECRET}" ]]; then
		echo "INFO: ${DIGIKUBE_GITHUB_ACCESS_TOKEN_SECRET} secret already available.  Reusing existing secret."
	else
		echo -n "Please enter the github.com access token : "
		read -s gitHubAccessToken </dev/tty
		echo -n ${gitHubAccessToken} | gcloud beta secrets create "${DIGIKUBE_GITHUB_ACCESS_TOKEN_SECRET}" --project="${DIGIKUBE_MASTER_PROJECT}" --labels="group=digikube,version=0_1" --locations="us-central1" --replication-policy="user-managed" --data-file=-
		if [[ $? -gt 0 ]]; then
			echo "ERROR: Error while creating ${DIGIKUBE_GITHUB_ACCESS_TOKEN_SECRET} secret"
		else
			echo "INFO: Created ${DIGIKUBE_GITHUB_ACCESS_TOKEN_SECRET} secret"
		fi
		unset gitHubAccessToken
	fi
fi
