#!/bin/bash
#All starts here

digikubeCodeRawRepoUrl="https://raw.githubusercontent.com/samdesh-gcp1/digikube-core/master"
digikubeInstanceRawRepoUrl="https://raw.githubusercontent.com/samdesh-gcp1/c1-dev1/master"
digikubeCoreRepoAccessToken=$(gcloud beta secrets versions access 1 --secret=digikube-github-access-token-secret --project=digikube-master3)

echo $digikubeCoreRepoAccessToken

exit 0

tmpExecDir=$(mktemp -d --suffix="-digikube")
bootstrapShell="${tmpExecDir}/bootstrap"
wget --no-cache \
	 --header="Authorization: token ${digikubeCoreRepoAccessToken}" \
	 -O ${bootstrapShell} - "${digikubeCodeRawRepoUrl}/cloud-init/bootstrap"
chmod +x ${bootstrapShell} ${bootstrapShell} ${digikubeCodeRawRepoUrl} ${digikubeInstanceRawRepoUrl} create
rm -rf "${tmpExecDir}"
digikubeCoreRepoAccessToken=""
unset digikubeCoreRepoAccessToken
