#!/bin/bash
#All starts here

############################################################################################
# Update the values as per your requirements
############################################################################################
digikubeCoreRawRepoUrl="https://raw.githubusercontent.com/samdesh-gcp1/digikube-core/master"
digikubeInstanceRawRepoUrl="https://raw.githubusercontent.com/samdesh-gcp1/c1-dev1/master"

#Following values are also set in bastion-init-shell...  be consistent
digikubeMasterProject="digikube-master3"
digikubeCoreRepoAccessTokenName="digikube-core-repo-access-token"
digikubeCoreRepoAccessTokenVersion="2"
digikubeInstanceRepoAccessTokenName="digikube-instance-repo-access-token"
digikubeInstanceRepoAccessTokenVersion="2"


digikubeCoreRepoAccessTokenValue=$(gcloud beta secrets versions access ${digikubeCoreRepoAccessTokenVersion} --secret=${digikubeCoreRepoAccessTokenName} --project=${digikubeMasterProject})
echo "${digikubeCoreRepoAccessTokenName}: ${digikubeCoreRepoAccessTokenVersion}: ${digikubeCoreRepoAccessTokenValue}"
digikubeInstanceRepoAccessTokenValue=$(gcloud beta secrets versions access ${digikubeInstanceRepoAccessTokenVersion} --secret=${digikubeInstanceRepoAccessTokenName} --project=${digikubeMasterProject})
echo "${digikubeInstanceRepoAccessTokenName}: ${digikubeInstanceRepoAccessTokenVersion}: ${digikubeInstanceRepoAccessTokenValue}"

tmpExecDir=$(mktemp -d --suffix="-digikube")
bootstrapShell="${tmpExecDir}/bootstrap"

echo "Hi 6"
echo $(ls ${bootstrapShell})
echo "Hi 7"

headerString="--header='Authorization: token ${digikubeCoreRepoAccessTokenValue}'"
echo $headerString
cmd1="wget --no-cache $headerString -O ${bootstrapShell} \"${digikubeCoreRawRepoUrl}/cloud-init/bootstrap\""

echo $cmd1

echo "Hi11

#$(${cmd1})
wget --no-cache "${headerString}" -O "${bootstrapShell}" "${digikubeCoreRawRepoUrl}/cloud-init/bootstrap"

echo "Hi15"

#wget --no-cache $headerString -O ${bootstrapShell} \"${digikubeCoreRawRepoUrl}/cloud-init/bootstrap\"

#wget --no-cache --header="Authorization: token ${digikubeCoreRepoAccessTokenValue}" -O ${bootstrapShell} - "${digikubeCoreRawRepoUrl}/cloud-init/bootstrap"
chmod +x ${bootstrapShell}
echo "${bootstrapShell} ${digikubeCoreRepoAccessTokenValue} ${digikubeCoreRawRepoUrl} ${digikubeInstanceRepoAccessTokenValue} ${digikubeInstanceRawRepoUrl} create"
${bootstrapShell} ${digikubeCoreRepoAccessTokenValue} ${digikubeCoreRawRepoUrl} ${digikubeInstanceRepoAccessTokenValue} ${digikubeInstanceRawRepoUrl} create
#rm -rf "${tmpExecDir}"
digikubeCoreRepoAccessToken=""
unset digikubeCoreRepoAccessToken
